'use client'

import { Icon } from '@iconify/react'

// Icon wrapper component that mimics lucide-react API
interface IconProps {
  className?: string
  size?: number | string
  strokeWidth?: number
  [key: string]: any
}

const createIcon = (name: string) => {
  return function IconComponent({ className, size, strokeWidth, ...props }: IconProps) {
    return (
      <Icon 
        icon={`lucide:${name}`} 
        className={className}
        width={size || 24}
        height={size || 24}
        {...props}
      />
    )
  }
}

// Export all used icons
export const Activity = createIcon('activity')
export const AlertTriangle = createIcon('alert-triangle')
export const ArrowLeft = createIcon('arrow-left')
export const ArrowRight = createIcon('arrow-right')
export const ArrowUp = createIcon('arrow-up')
export const BookOpen = createIcon('book-open')
export const Box = createIcon('box')
export const Briefcase = createIcon('briefcase')
export const Building = createIcon('building')
export const Building2 = createIcon('building-2')
export const Calculator = createIcon('calculator')
export const Calendar = createIcon('calendar')
export const Camera = createIcon('camera')
export const Check = createIcon('check')
export const CheckCircle = createIcon('check-circle')
export const ChevronDown = createIcon('chevron-down')
export const ChevronRight = createIcon('chevron-right')
export const ChevronUp = createIcon('chevron-up')
export const ChevronsUpDown = createIcon('chevrons-up-down')
export const Circle = createIcon('circle')
export const Clock = createIcon('clock')
export const Code = createIcon('code')
export const DollarSign = createIcon('dollar-sign')
export const Edit = createIcon('edit')
export const ExternalLink = createIcon('external-link')
export const Eye = createIcon('eye')
export const Facebook = createIcon('facebook')
export const FileText = createIcon('file-text')
export const FolderOpen = createIcon('folder-open')
export const Gamepad2 = createIcon('gamepad-2')
export const Globe = createIcon('globe')
export const Heart = createIcon('heart')
export const HelpCircle = createIcon('help-circle')
export const Home = createIcon('home')
export const Info = createIcon('info')
export const Instagram = createIcon('instagram')
export const Layers = createIcon('layers')
export const Leaf = createIcon('leaf')
export const Lightbulb = createIcon('lightbulb')
export const Linkedin = createIcon('linkedin')
export const List = createIcon('list')
export const Loader2 = createIcon('loader-2')
export const Lock = createIcon('lock')
export const LogOut = createIcon('log-out')
export const Mail = createIcon('mail')
export const MapPin = createIcon('map-pin')
export const Megaphone = createIcon('megaphone')
export const Menu = createIcon('menu')
export const MessageCircle = createIcon('message-circle')
export const MessageSquare = createIcon('message-square')
export const Minus = createIcon('minus')
export const Monitor = createIcon('monitor')
export const Moon = createIcon('moon')
export const Package = createIcon('package')
export const Palette = createIcon('palette')
export const Pen = createIcon('pen')
export const Phone = createIcon('phone')
export const Plane = createIcon('plane')
export const Plus = createIcon('plus')
export const PlusIcon = createIcon('plus')
export const Rocket = createIcon('rocket')
export const Save = createIcon('save')
export const Search = createIcon('search')
export const SearchIcon = createIcon('search')
export const Send = createIcon('send')
export const Share2 = createIcon('share-2')
export const Shield = createIcon('shield')
export const Shirt = createIcon('shirt')
export const ShoppingCart = createIcon('shopping-cart')
export const Smartphone = createIcon('smartphone')
export const Sparkles = createIcon('sparkles')
export const Star = createIcon('star')
export const Sun = createIcon('sun')
export const Tag = createIcon('tag')
export const Target = createIcon('target')
export const Trash2 = createIcon('trash-2')
export const TrendingUp = createIcon('trending-up')
export const User = createIcon('user')
export const Users = createIcon('users')
export const Video = createIcon('video')
export const Wifi = createIcon('wifi')
export const X = createIcon('x')
export const Cpu = createIcon('cpu')
export const Coffee = createIcon('coffee')
export const Film = createIcon('film')
export const BarChart = createIcon('bar-chart')
export const Award = createIcon('award')
export const BookMarked = createIcon('book-marked')
export const Layout = createIcon('layout')
export const LayoutDashboard = createIcon('layout-dashboard')
export const MousePointer = createIcon('mouse-pointer')
export const Music = createIcon('music')
export const PenTool = createIcon('pen-tool')
export const Scissors = createIcon('scissors')
export const Server = createIcon('server')
export const Tablet = createIcon('tablet')
export const Wrench = createIcon('wrench')
export const Zap = createIcon('zap')
export const Image = createIcon('image')
export const ImageIcon = createIcon('image')
export const Play = createIcon('play')
export const UserCheck = createIcon('user-check')
export const Pencil = createIcon('pencil')
export const MoreHorizontal = createIcon('more-horizontal')
export const MoreVertical = createIcon('more-vertical')
export const Settings = createIcon('settings')
export const Trash = createIcon('trash')
export const Copy = createIcon('copy')
export const Download = createIcon('download')
export const Upload = createIcon('upload')
export const RefreshCw = createIcon('refresh-cw')
export const AlertCircle = createIcon('alert-circle')
export const XCircle = createIcon('x-circle')
export const ChevronLeft = createIcon('chevron-left')
export const Newspaper = createIcon('newspaper')
export const BadgeCheck = createIcon('badge-check')
